project:
  type: book
  output-dir: docs

book:
  title: "Kenai River Baseline Water Quality Project Data QA/QC Years 2014 - 2025"
  author: "Benjamin Meyer, Kenai Watershed Forum"
  date: "`r Sys.Date()`"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - part: "Years"
      chapters: 
      - project_year/2014.qmd
      - project_year/2015.qmd
      - project_year/2016.qmd
      - project_year/2017.qmd
      - project_year/2018.qmd
      - project_year/2019.qmd
      - project_year/2020.qmd
      - project_year/2021.qmd
      - project_year/2022.qmd
      - project_year/2023.qmd
      - project_year/2024.qmd
      - project_year/2025.qmd

    
  repo-url: https://github.com/Kenai-Watershed-Forum/kenai-river-wqx-qaqc
  search:
    location: sidebar
    type: textbox
  downloads: [docx]
    
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github
  #pdf:
  #  documentclass: scrreprt
  


editor: visual

