project:
  type: book
  output-dir: docs

book:
  title: "Kenai River Baseline Water Quality Project Data QA/QC Year XXXX - XXXX"
  author: "Benjamin Meyer, Kenai Watershed Forum"
  date: "12/15/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
  repo-url: https://github.com/Kenai-Watershed-Forum/kenai-river-wqx-qaqc
  search:
    location: sidebar
    type: textbox
  downloads: [docx]
    
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github
  #pdf:
  #  documentclass: scrreprt
  


editor: visual

